-- 코드를 입력하세요
SELECT
    A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM
    ANIMAL_INS A
INNER JOIN
    ANIMAL_OUTS B USING (ANIMAL_ID)
WHERE
    SEX_UPON_INTAKE LIKE 'Intact%'
    AND SEX_UPON_OUTCOME  NOT LIKE 'Intact%'
ORDER BY
    A.ANIMAL_ID;