-- 코드를 입력하세요
SELECT
    CASE
        WHEN PRICE >= 10000 THEN CONCAT(LEFT(PRICE, 1), '0000')
        WHEN PRICE < 10000 THEN '0'
        
    END AS PRICE_GROUP,
    COUNT(CONCAT(LEFT(PRICE, 1), '0000')) AS PRODUCTS
FROM
    PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE;