-- 코드를 입력하세요
SELECT
    APNT_NO, PT_NAME, PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM
    APPOINTMENT A
INNER JOIN
    PATIENT B USING (PT_NO)
INNER JOIN DOCTOR C
    ON A.MDDR_ID = C.DR_ID
    
WHERE
    APNT_YMD LIKE '2022-04-13%'
    AND APNT_CNCL_YN = 'N'
    AND A.MCDP_CD = 'CS'
ORDER BY 
    APNT_YMD;