-- 코드를 입력하세요
SELECT
    DISTINCT CAR_ID
FROM
    CAR_RENTAL_COMPANY_CAR A
INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY B USING (CAR_ID)
WHERE
    CAR_TYPE = '세단'
    AND START_DATE LIKE '2022-10%'
ORDER BY
    A.CAR_ID DESC;