-- 코드를 입력하세요
SELECT
    A.ANIMAL_ID, A.NAME
FROM
    ANIMAL_INS A
INNER JOIN 
    ANIMAL_OUTS B USING (ANIMAL_ID)
WHERE
    DATEDIFF(A.DATETIME, B.DATETIME) >= 0
    AND TIMEDIFF(A.DATETIME, B.DATETIME) > 0
ORDER BY
    A.DATETIME;